//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class expense_category : XPLiteObject
    {
        int fexpense_category_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int expense_category_id
        {
            get { return fexpense_category_id; }
            set { SetPropertyValue<int>(nameof(expense_category_id), ref fexpense_category_id, value); }
        }
        string fexpense_category_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Maintenance Category")]
        [DevExpress.Persistent.Validation.RuleRequiredField("expense_category_expense_category_name_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Maintenance Category")]
        public string expense_category_name
        {
            get { return fexpense_category_name; }
            set { SetPropertyValue<string>(nameof(expense_category_name), ref fexpense_category_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Expense Type Categories")]
        [Association(@"expense_type_categoryReferencesexpense_category")]
        public XPCollection<expense_type_category> expense_type_categorys { get { return GetCollection<expense_type_category>(nameof(expense_type_categorys)); } }
        [DevExpress.Xpo.DisplayName(@"Truck Expenses")]
        [Association(@"truck_expenseReferencesexpense_category")]
        public XPCollection<truck_expense> truck_expenses { get { return GetCollection<truck_expense>(nameof(truck_expenses)); } }
    }

}
