//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class expense_type_category : XPLiteObject
    {
        int fexpense_type_category_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int expense_type_category_id
        {
            get { return fexpense_type_category_id; }
            set { SetPropertyValue<int>(nameof(expense_type_category_id), ref fexpense_type_category_id, value); }
        }
        expense_type fexpense_type_id;
        [Indexed(@"expense_category_id", Name = @"inx_expense_type_category_uni", Unique = true)]
        [Association(@"expense_type_categoryReferencesexpense_type")]
        [DevExpress.Xpo.DisplayName(@"Expense Type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("expense_type_category_expense_type_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Expense Type")]
        public expense_type expense_type_id
        {
            get { return fexpense_type_id; }
            set { SetPropertyValue<expense_type>(nameof(expense_type_id), ref fexpense_type_id, value); }
        }
        expense_category fexpense_category_id;
        [Association(@"expense_type_categoryReferencesexpense_category")]
        [DevExpress.Xpo.DisplayName(@"Maintenance Category")]
        [DevExpress.Persistent.Validation.RuleRequiredField("expense_type_category_expense_category_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Maintenance Category")]
        public expense_category expense_category_id
        {
            get { return fexpense_category_id; }
            set { SetPropertyValue<expense_category>(nameof(expense_category_id), ref fexpense_category_id, value); }
        }
    }

}
