//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class location : XPLiteObject
    {
        int flocation_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int location_id
        {
            get { return flocation_id; }
            set { SetPropertyValue<int>(nameof(location_id), ref flocation_id, value); }
        }
        string flocation_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Location")]
        [DevExpress.Persistent.Validation.RuleRequiredField("location_location_name_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Location")]
        public string location_name
        {
            get { return flocation_name; }
            set { SetPropertyValue<string>(nameof(location_name), ref flocation_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Trucks")]
        [Association(@"truckReferenceslocation")]
        public XPCollection<truck> trucks { get { return GetCollection<truck>(nameof(trucks)); } }
        [DevExpress.Xpo.DisplayName(@"Truck Expenses")]
        [Association(@"truck_expenseReferenceslocation")]
        public XPCollection<truck_expense> truck_expenses { get { return GetCollection<truck_expense>(nameof(truck_expenses)); } }
        [DevExpress.Xpo.DisplayName(@"User Locations")]
        [Association(@"user_locationReferenceslocation")]
        public XPCollection<user_location> user_locations { get { return GetCollection<user_location>(nameof(user_locations)); } }
    }

}
