//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class truck_km : XPLiteObject
    {
        int ftruck_km_id;
        [Key]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int truck_km_id
        {
            get { return ftruck_km_id; }
            set { SetPropertyValue<int>(nameof(truck_km_id), ref ftruck_km_id, value); }
        }
        truck ftruck_id;
        [Association(@"truck_kmReferencestruck")]
        [DevExpress.Xpo.DisplayName(@"Truck")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_km_truck_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Truck")]
        public truck truck_id
        {
            get { return ftruck_id; }
            set { SetPropertyValue<truck>(nameof(truck_id), ref ftruck_id, value); }
        }
        double fkm_amount;
        [DevExpress.Xpo.DisplayName(@"KM amount")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_km_km_amount_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter KM amount")]
        public double km_amount
        {
            get { return fkm_amount; }
            set { SetPropertyValue<double>(nameof(km_amount), ref fkm_amount, value); }
        }
        DateTime ftruck_km_date;
        [DevExpress.Xpo.DisplayName(@"Date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_km_truck_km_date_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Date")]
        public DateTime truck_km_date
        {
            get { return ftruck_km_date; }
            set { SetPropertyValue<DateTime>(nameof(truck_km_date), ref ftruck_km_date, value); }
        }
    }

}
