//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class truck : XPLiteObject
    {
        int ftruck_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int truck_id
        {
            get { return ftruck_id; }
            set { SetPropertyValue<int>(nameof(truck_id), ref ftruck_id, value); }
        }
        string fplate;
        [Indexed(Name = @"inx_truck_plate_uni", Unique = true)]
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Plate")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_plate_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Plate")]
        public string plate
        {
            get { return fplate; }
            set { SetPropertyValue<string>(nameof(plate), ref fplate, value); }
        }
        string fequipment_number;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Equipment Number")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_equipment_number_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Equipment Number")]
        public string equipment_number
        {
            get { return fequipment_number; }
            set { SetPropertyValue<string>(nameof(equipment_number), ref fequipment_number, value); }
        }
        location flocation_id;
        [Association(@"truckReferenceslocation")]
        [DevExpress.Xpo.DisplayName(@"Location")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_location_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Location")]
        public location location_id
        {
            get { return flocation_id; }
            set { SetPropertyValue<location>(nameof(location_id), ref flocation_id, value); }
        }
        string ftruck_type;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Truck Type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_truck_type_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Truck Type")]
        public string truck_type
        {
            get { return ftruck_type; }
            set { SetPropertyValue<string>(nameof(truck_type), ref ftruck_type, value); }
        }
        string ftruck_model;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Truck Model")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_truck_model_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Truck Model")]
        public string truck_model
        {
            get { return ftruck_model; }
            set { SetPropertyValue<string>(nameof(truck_model), ref ftruck_model, value); }
        }
        string ftruck_box;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Truck Box")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_truck_box_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Truck Box")]
        public string truck_box
        {
            get { return ftruck_box; }
            set { SetPropertyValue<string>(nameof(truck_box), ref ftruck_box, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Truck Expenses")]
        [Association(@"truck_expenseReferencestruck")]
        public XPCollection<truck_expense> truck_expenses { get { return GetCollection<truck_expense>(nameof(truck_expenses)); } }
        [DevExpress.Xpo.DisplayName(@"Truck KMs")]
        [Association(@"truck_kmReferencestruck")]
        public XPCollection<truck_km> truck_kms { get { return GetCollection<truck_km>(nameof(truck_kms)); } }
    }

}
