//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class truck_expense : XPLiteObject
    {
        int ftruck_expense_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int truck_expense_id
        {
            get { return ftruck_expense_id; }
            set { SetPropertyValue<int>(nameof(truck_expense_id), ref ftruck_expense_id, value); }
        }
        DateTime ftrk_exp_date;
        [DevExpress.Xpo.DisplayName(@"Date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_trk_exp_date_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Date")]
        public DateTime trk_exp_date
        {
            get { return ftrk_exp_date; }
            set { SetPropertyValue<DateTime>(nameof(trk_exp_date), ref ftrk_exp_date, value); }
        }
        truck ftruck_id;
        [Association(@"truck_expenseReferencestruck")]
        [DevExpress.Xpo.DisplayName(@"Truck")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_truck_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Truck")]
        public truck truck_id
        {
            get { return ftruck_id; }
            set { SetPropertyValue<truck>(nameof(truck_id), ref ftruck_id, value); }
        }
        location flocation_id;
        [Association(@"truck_expenseReferenceslocation")]
        [DevExpress.Xpo.DisplayName(@"Location")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_location_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Location")]
        public location location_id
        {
            get { return flocation_id; }
            set { SetPropertyValue<location>(nameof(location_id), ref flocation_id, value); }
        }
        expense_type fexpense_type_id;
        [Association(@"truck_expenseReferencesexpense_type")]
        [DevExpress.Xpo.DisplayName(@"Expense Type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_expense_type_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Expense Type")]
        public expense_type expense_type_id
        {
            get { return fexpense_type_id; }
            set { SetPropertyValue<expense_type>(nameof(expense_type_id), ref fexpense_type_id, value); }
        }
        expense_category fexpense_category_id;
        [Association(@"truck_expenseReferencesexpense_category")]
        [DevExpress.Xpo.DisplayName(@"Maintenance Category")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_expense_category_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Maintenance Category")]
        public expense_category expense_category_id
        {
            get { return fexpense_category_id; }
            set { SetPropertyValue<expense_category>(nameof(expense_category_id), ref fexpense_category_id, value); }
        }
        payment_type fpayment_type_id;
        [Association(@"truck_expenseReferencespayment_type")]
        [DevExpress.Xpo.DisplayName(@"Payment Type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_payment_type_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Payment Type")]
        public payment_type payment_type_id
        {
            get { return fpayment_type_id; }
            set { SetPropertyValue<payment_type>(nameof(payment_type_id), ref fpayment_type_id, value); }
        }
        vendor fvendor_id;
        [Association(@"truck_expenseReferencesvendor")]
        [DevExpress.Xpo.DisplayName(@"Vendor")]
        public vendor vendor_id
        {
            get { return fvendor_id; }
            set { SetPropertyValue<vendor>(nameof(vendor_id), ref fvendor_id, value); }
        }
        string finvoice_number;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Invoice Number")]
        public string invoice_number
        {
            get { return finvoice_number; }
            set { SetPropertyValue<string>(nameof(invoice_number), ref finvoice_number, value); }
        }
        double famount;
        [DevExpress.Xpo.DisplayName(@"Amount")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_amount_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Amount")]
        public double amount
        {
            get { return famount; }
            set { SetPropertyValue<double>(nameof(amount), ref famount, value); }
        }
        double fvat;
        [DevExpress.Xpo.DisplayName(@"VAT")]
        public double vat
        {
            get { return fvat; }
            set { SetPropertyValue<double>(nameof(vat), ref fvat, value); }
        }
        double ftotal_amount;
        [DevExpress.Xpo.DisplayName(@"Total Amount")]
        [DevExpress.Persistent.Validation.RuleRequiredField("truck_expense_total_amount_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Total Amount")]
        public double total_amount
        {
            get { return ftotal_amount; }
            set { SetPropertyValue<double>(nameof(total_amount), ref ftotal_amount, value); }
        }
        string fcomments;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Comments")]
        public string comments
        {
            get { return fcomments; }
            set { SetPropertyValue<string>(nameof(comments), ref fcomments, value); }
        }
    }

}
