//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class user_location : XPLiteObject
    {
        int fuser_location_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int user_location_id
        {
            get { return fuser_location_id; }
            set { SetPropertyValue<int>(nameof(user_location_id), ref fuser_location_id, value); }
        }
        location flocation_id;
        [Association(@"user_locationReferenceslocation")]
        [DevExpress.Xpo.DisplayName(@"Location")]
        [DevExpress.Persistent.Validation.RuleRequiredField("user_location_location_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Location")]
        public location location_id
        {
            get { return flocation_id; }
            set { SetPropertyValue<location>(nameof(location_id), ref flocation_id, value); }
        }
        DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser fuser_id;
        [DevExpress.Xpo.DisplayName(@"User")]
        [DevExpress.Persistent.Validation.RuleRequiredField("user_location_user_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter User")]
        public DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser user_id
        {
            get { return fuser_id; }
            set { SetPropertyValue<DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser>(nameof(user_id), ref fuser_id, value); }
        }
    }

}
