//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroTruckLogistics.Module.BO
{

    public partial class vendor : XPLiteObject
    {
        long fvendor_id;
        [Key]
        [DevExpress.Xpo.DisplayName(@"Vendor Number")]
        [DevExpress.Persistent.Validation.RuleRequiredField("vendor_vendor_id_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Vendor Number")]
        public long vendor_id
        {
            get { return fvendor_id; }
            set { SetPropertyValue<long>(nameof(vendor_id), ref fvendor_id, value); }
        }
        string fvendor_name;
        [DevExpress.Xpo.DisplayName(@"Vendor Name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("vendor_vendor_name_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Vendor Name")]
        public string vendor_name
        {
            get { return fvendor_name; }
            set { SetPropertyValue<string>(nameof(vendor_name), ref fvendor_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Truck Expenses")]
        [Association(@"truck_expenseReferencesvendor")]
        public XPCollection<truck_expense> truck_expenses { get { return GetCollection<truck_expense>(nameof(truck_expenses)); } }
    }

}
